# -*- coding: utf-8 -*-
"""conversão de relatorio e teste

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jdvmYF7SlmUzSVz6ogpbFSFtJk-G4jCz
"""

# ============================================================
# parser_anafas_v28.py
# ============================================================
# Este Código realiza o parsing de um relatório ANAFAS (.txt)
# e gera um arquivo Excel com duas abas:
#   1. "DadosBrutos" → informações detalhadas de faltas e contribuições
#   2. "Analise_Evento" → resumo consolidado com métricas calculadas
#
# Funcionalidades:
# - Criação de identificador único de circuito
# - Cálculo de impedâncias e correntes
# - Detecção de tipos de falta (FFF, FF, FT)
# - Análise de eventos para múltiplos tipos de circuito L(tipo linha
# - Criação automática de tabelas Excel formatadas
# - Exportação adicional em formato CSV
# ============================================================

import re
import pandas as pd
import numpy as np
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.utils import get_column_letter

# ============================================================
# CONFIGURAÇÃO BÁSICA
# ============================================================
INPUT = "relatorio.txt"                                # Arquivo de entrada
OUT_XLSX = "relatorio_anafas_processado.xlsx"          # Saída Excel
OUT_CSV = "relatorio_anafas_processado.csv"            # Saída CSV dados brutos
OUT_CSV_ANALISE = "relatorio_anafas_analise_evento.csv"# Saída Csv Analise Evento
PHASES = ["A", "B", "C", "P", "N", "Z"]                # Fases possíveis
IMP_COMBS = ["AB", "AN", "BC", "BN", "CA", "CN"]       # Combinações de impedância

# ============================================================
# FUNÇÕES AUXILIARES
# ============================================================

def to_num_or_none(s):
    """Converte string para float, retornando None se inválido."""
    if s is None:
        return None
    s = str(s).strip().replace(",", ".")
    try:
        return float(s)
    except:
        return None

def split_minus_fix(line):
    """Corrige casos onde há sinal '-' entre números sem espaço."""
    return re.sub(r'(?<=\d)-(?=\d)', ' -', line)

def create_id_code(circuito, barra_origem, barra_destino):
    """
    Gera um código único de identificação baseado no circuito,
    barra de origem e barra de destino.
    """
    circuito = str(circuito or "").strip()
    bo = str(barra_origem or "").strip()
    bd = str(barra_destino or "").strip()
    circuito_right_4 = circuito[-4:] if circuito else "N/A"
    bo_left_4 = bo[:4] if bo else "N/A"
    bd_left_4 = bd[:4] if bd else "N/A"
    circuito_left_2 = circuito[:2] if circuito else "N/A"
    return f"{circuito_right_4}-{bo_left_4}-{bd_left_4}-{circuito_left_2}"

# ============================================================
# EXPRESSÕES REGULARES (para identificar seções e dados)
# ============================================================
re_case = re.compile(r"^\s*(\d+)\s+(\w+)\s+(.+?)\s{2,}(.+)$")
re_bar = re.compile(r"Bar\.?\s*(\d+)\s*\(([^)]+)\)", re.IGNORECASE)
re_circuit = re.compile(r"Cir\.\s*([^\s]+)", re.IGNORECASE)
re_triple = re.compile(r'([A-Za-z]{1,3})\s*([+-]?\d+(?:[.,]\d+)?)\s*([+-]?\d+(?:[.,]\d+)?)')

# ============================================================
# LEITURA DO ARQUIVO DE ENTRADA
# ============================================================
try:
    with open(INPUT, "r", encoding="latin-1") as f:
        lines = [ln.rstrip("\n") for ln in f]
except FileNotFoundError:
    print(f"ERRO: Arquivo de entrada '{INPUT}' não encontrado.")
    exit()

# Variáveis de controle
rows = []
i = 0
current_case = None
secao = None
curto_info = {"id": None, "nome": None, "tensao": {}, "corrente": {}}
origem_contrib = {"id": None, "nome": None, "tensao": {}}

# ============================================================
# PARSER PRINCIPAL DO ARQUIVO ANAFAS
# ============================================================
while i < len(lines):
    raw = lines[i]
    line = raw.strip()

    # Ignora cabeçalhos institucionais
    if "CEPEL - Centro" in raw or "ANAFAS" in raw:
        i += 1
        continue

    # Identifica novo caso
    mcase = re_case.match(line)
    if mcase:
        current_case = {
            "Caso": mcase.group(1),
            "Falta": mcase.group(2),
            "Localizacao": mcase.group(3).strip(),
            "Contingencia": mcase.group(4).strip()
        }
        curto_info = {"id": None, "nome": None, "tensao": {}, "corrente": {}}
        origem_contrib = {"id": None, "nome": None, "tensao": {}}
        secao = None
        i += 1
        continue

    # Define qual seção do relatório está sendo lida
    tnorm = re.sub(r"\s+", "", line).upper()
    if "CURTO" in tnorm:
        secao = "CURTO"; i += 1; continue
    if "CONTRIB" in tnorm:
        secao = "CONTRIB"; i += 1; continue

    # ========================================================
    # SEÇÃO CURTO-CIRCUITO
    # ========================================================
    if secao == "CURTO":
        mbar = re_bar.search(raw)
        if mbar:
            curto_info["id"] = mbar.group(1)
            curto_info["nome"] = mbar.group(2).strip()
            curto_info["tensao"], curto_info["corrente"] = {}, {}
            i += 1
            continue

        # Captura tensões e correntes por fase
        if re.match(r'^[A-Za-z]', line):
            lproc = split_minus_fix(raw)
            triples = re_triple.findall(lproc)
            triples = [(lab.upper(), to_num_or_none(v1), to_num_or_none(v2))
                       for (lab, v1, v2) in triples if lab.upper() != "G"]
            if triples:
                half = len(triples)//2 if len(triples) >= 2 else len(triples)
                for lab, m, a in triples[:half]:
                    if lab in PHASES:
                        curto_info["tensao"][lab] = (m, a)
                for lab, m, a in triples[half:]:
                    if lab in PHASES:
                        curto_info["corrente"][lab] = (m, a)
        i += 1
        continue

    # ========================================================
    # SEÇÃO CONTRIBUIÇÃO DE BARRAS E CIRCUITOS
    # ========================================================
    if secao == "CONTRIB":
        mbar = re_bar.search(raw)
        if mbar:
            barra_id, barra_nome = mbar.group(1), mbar.group(2).strip()
            circ_m = re_circuit.search(raw)

            # Caso sem circuito
            if not circ_m:
                origem_contrib["id"], origem_contrib["nome"] = barra_id, barra_nome
                origem_contrib["tensao"] = {}
                j = i + 1
                while j < len(lines) and not re_bar.search(lines[j]) and not re_case.match(lines[j]):
                    ln_raw = lines[j]
                    ln_proc = split_minus_fix(ln_raw)
                    triples = re_triple.findall(ln_proc)
                    triples = [(l.upper(), to_num_or_none(mv), to_num_or_none(av)) for (l, mv, av) in triples]
                    for lab, m, a in triples:
                        if lab in PHASES:
                            origem_contrib["tensao"][lab] = (m, a)
                    j += 1
                i = j
                continue

            # Caso com circuito — coleta tensões, correntes e impedâncias
            circuito = circ_m.group(1).strip()
            dest_tens, dest_corr, imp_map = {}, {}, {}
            j = i + 1
            while j < len(lines):
                ln_raw = lines[j]
                if not ln_raw.strip():
                    j += 1; continue
                if re_bar.search(ln_raw) or re_case.match(ln_raw) or \
                   "CEPEL - Centro" in ln_raw or "ANAFAS" in ln_raw:
                    break
                lp = split_minus_fix(ln_raw)
                triples = re_triple.findall(lp)
                triples = [(l.upper(), to_num_or_none(mv), to_num_or_none(av)) for (l, mv, av) in triples if l.upper() != "G"]
                if triples:
                    one_letter = [(l, m, a) for (l, m, a) in triples if len(l) == 1 and l in PHASES]
                    two_letter = [(l, m, a) for (l, m, a) in triples if len(l) > 1]
                    if one_letter:
                        for l, m, a in one_letter:
                            if l not in dest_tens:
                                dest_tens[l] = (m, a)
                            else:
                                dest_corr[l] = (m, a)
                    for l, m, a in two_letter:
                        imp_map[l] = (m, a)
                j += 1

            # Gera código de identificação
            identificacao_bloco = create_id_code(circuito, origem_contrib.get('id',''), barra_id)

            # Linha base do registro
            base_row = {
                "Caso": current_case.get("Caso"),
                "Falta": current_case.get("Falta"),
                "Localizacao": current_case.get("Localizacao"),
                "Contingencia": current_case.get("Contingencia"),
                "BarraOrigem": f"{origem_contrib.get('id','')} {origem_contrib.get('nome','')}".strip(),
                "BarraDestino": f"{barra_id} {barra_nome}",
                "Circuito": circuito,
                "Identificacao": identificacao_bloco
            }

            # Mapeamento de impedâncias
            has_impedance_data = bool(imp_map)
            impedancias_ordenadas = [imp_map.get(comb, (None, None)) for comb in IMP_COMBS]

            # Gera linhas por fase
            for k, ph in enumerate(PHASES):
                row = base_row.copy()
                if has_impedance_data and k < len(IMP_COMBS):
                    ponto_imp = IMP_COMBS[k]
                    m, a = impedancias_ordenadas[k]
                    row["Impedancia_Ponto"] = ponto_imp
                    row["Impedancia_Mod"] = to_num_or_none(m)
                    row["Impedancia_Ang"] = to_num_or_none(a)
                else:
                    row["Impedancia_Ponto"] = None
                    row["Impedancia_Mod"] = None
                    row["Impedancia_Ang"] = None

                # Dados de tensão e corrente
                row.update({
                    "Fase": ph,
                    "TensaoModuloCurto": curto_info["tensao"].get(ph, (None, None))[0],
                    "TensaoAnguloCurto": curto_info["tensao"].get(ph, (None, None))[1],
                    "CorrenteModuloCurto": curto_info["corrente"].get(ph, (None, None))[0],
                    "CorrenteAnguloCurto": curto_info["corrente"].get(ph, (None, None))[1],
                    "TensaoModuloOrigem": origem_contrib["tensao"].get(ph, (None, None))[0],
                    "TensaoAnguloOrigem": origem_contrib["tensao"].get(ph, (None, None))[1],
                    "TensaoModuloDestino": dest_tens.get(ph, (None, None))[0],
                    "TensaoAnguloDestino": dest_tens.get(ph, (None, None))[1],
                    "CorrenteModuloCircuito": dest_corr.get(ph, (None, None))[0],
                    "CorrenteAnguloCircuito": dest_corr.get(ph, (None, None))[1],
                })
                rows.append(row)
            i = j
            continue
    i += 1

# ============================================================
# CONSTRUÇÃO DO DATAFRAME PRINCIPAL (Dados Brutos)
# ============================================================
cols = [
    "Caso","Falta","Localizacao","Contingencia","Fase",
    "TensaoModuloCurto","TensaoAnguloCurto","CorrenteModuloCurto","CorrenteAnguloCurto",
    "BarraOrigem","TensaoModuloOrigem","TensaoAnguloOrigem",
    "BarraDestino","TensaoModuloDestino","TensaoAnguloDestino",
    "Circuito","CorrenteModuloCircuito","CorrenteAnguloCircuito",
    "Identificacao",
    "Impedancia_Ponto", "Impedancia_Mod", "Impedancia_Ang"
]

df = pd.DataFrame(rows)
for c in cols:
    if c not in df.columns:
        df[c] = None
df = df[cols]

# Conversão de colunas de impedância para float
for col_imp in ["Impedancia_Mod", "Impedancia_Ang"]:
    df[col_imp] = pd.to_numeric(df[col_imp], errors='coerce')

# ============================================================
# ABA "Analise_Evento"
# ============================================================

analise_rows = []
if not df.empty:
    df["Identificacao"] = df["Identificacao"].astype(str).fillna("").str.strip()
    filtro_L = df[df["Identificacao"].str.contains(r"-\w*L$", na=False)]

    if not filtro_L.empty:
        for ident, sub in filtro_L.groupby("Identificacao"):
            # Subdivide entre CASO e CLOSE
            base = sub[sub["Contingencia"].str.contains("CASO", case=False, na=False)]
            close = sub[sub["Contingencia"].str.contains("CLOSE", case=False, na=False)]

            # Subdivide por tipo de falta
            base_FFF = base[base["Falta"].str.contains("FFF", na=False)]
            base_FF  = base[base["Falta"].str.contains("FF", na=False) & ~base["Falta"].str.contains("FFF", na=False)]
            base_FT  = base[base["Falta"].str.contains("FT", na=False)]
            close_FFF = close[close["Falta"].str.contains("FFF", na=False)]
            close_FT  = close[close["Falta"].str.contains("FT", na=False)]

            # Função para pegar o primeiro valor numérico válido
            def get_num(df_in, fase, col):
                if df_in.empty:
                    return np.nan
                vals = df_in[df_in["Fase"] == fase][col].values
                for v in vals:
                    if isinstance(v, (int, float)):
                        return float(v)
                    if pd.isna(v):
                        return np.nan
                    if isinstance(v, str):
                        try:
                            return float(v)
                        except:
                            pass
                return np.nan

            # --- Cálculos principais ---
            ia_cc3f = get_num(base_FFF, "A", "CorrenteModuloCircuito")      #  Corrente de curto trifásico (FFF) na fase A.
            ang_ia_cc3f = get_num(base_FFF, "A", "CorrenteAnguloCircuito")  #  Ângulo da corrente de curto trifásico (FFF) na fase A.
            ib_cc2f = get_num(base_FF, "B", "CorrenteModuloCircuito")       #  Corrente de curto bifásico (FF) na fase B.(bifasico a fase A é nula)
            ang_ib_cc2f = get_num(base_FF, "B", "CorrenteAnguloCircuito")   #  Ângulo da corrente de curto bifásico (FF) na fase B
            ia_cc1f = get_num(base_FT, "A", "CorrenteModuloCircuito")       #  Corrente de curto monofásico (FT) na fase A.
            ang_ia_cc1f = get_num(base_FT, "A", "CorrenteAnguloCircuito")   #  Ângulo da corrente de curto monofásico (FT) na fase A.
            i0_ft = get_num(base_FT, "Z", "CorrenteModuloCircuito")         #  Componente homopolar do curto FT  da fase Z x 3.
            ang_i0_ft = get_num(base_FT, "Z", "CorrenteAnguloCircuito")     #  Ângulo da correspondente do componente homopolar
            i0_ft_3x = i0_ft * 3 if pd.notna(i0_ft) else np.nan             #  Multiplicação Z x 3.

            # Impedância AN
            zan_row = sub[sub["Impedancia_Ponto"] == "AN"]
            zan = get_num(zan_row, zan_row["Fase"].values[0] if not zan_row.empty else "A", "Impedancia_Mod")  #  Impedância equivalente da falta FT (ponto AN do circuito).
            zang = get_num(zan_row, zan_row["Fase"].values[0] if not zan_row.empty else "A", "Impedancia_Ang") #  Ângulo Correspondente da Impedancia no ponto AN

            # Calculos dos casos Close-in
            ci_A = get_num(close_FT, "A", "CorrenteModuloCircuito")        #  Modulo da Corrente  na falta FT durante simulação CLOSE-IN na fase A.
            ci_ang_A = get_num(close_FT, "A", "CorrenteAnguloCircuito")    #  Ângulo da corrente na falta FT durante a simulação CLOSE-IN na fase A.
            ci_A3 = ci_A * 3 if pd.notna(ci_A) else np.nan                 #  Multiplicação (A x 3) devido a ser falta do tipo FT
            ci_fff = get_num(close_FFF, "A", "CorrenteModuloCircuito")     #  Modulo da Corrente  na falta FFF durante simulação CLOSE-IN na fase A.
            ci_ang_fff = get_num(close_FFF, "A", "CorrenteAnguloCircuito") #  Ângulo da corrente na falta FFF durante a simulação CLOSE-IN na fase A.

            loc = sub["Localizacao"].dropna().values[0] if not sub["Localizacao"].dropna().empty else "N/A"

            analise_rows.append({
                "Identificacao": ident,
                "Localizacao": loc,
                "IA_CC3F": ia_cc3f, "ANG_IA_CC3F": ang_ia_cc3f,
                "IB_CC2F": ib_cc2f, "ANG_IB_CC2F": ang_ib_cc2f,
                "IA_CCFT": ia_cc1f, "ANG_IA_CCFT": ang_ia_cc1f,
                "X3I0_CCFT": i0_ft_3x, "ANG_3I0_CCFT": ang_i0_ft,
                "Zan_CCFT": zan, "ANG_Zan_CCFT": zang,
                "X3I0_FT_CloseIn": ci_A3, "ANG_3I0_FT_CloseIn": ci_ang_A,
                "IA_FFF_CloseIn": ci_fff, "ANG_IA_FFF_CloseIn": ci_ang_fff
            })

df_analise = pd.DataFrame(analise_rows)

# ============================================================
# EXPORTAÇÃO PARA EXCEL E CSV
# ============================================================
with pd.ExcelWriter(OUT_XLSX, engine="openpyxl", mode="w") as writer:
    # Aba 1: Dados brutos
    df.to_excel(writer, sheet_name="DadosBrutos", index=False)

    # Aba 2: Análise de evento (tabela começa na linha 5)
    df_analise.to_excel(writer, sheet_name="Analise_Evento", index=False, startrow=4)

    workbook = writer.book
    style = TableStyleInfo(name="TableStyleMedium9", showRowStripes=True)

    # --- Tabela da aba DadosBrutos ---
    sheet1 = workbook["DadosBrutos"]
    range_tabela1 = f"A1:{get_column_letter(df.shape[1])}{df.shape[0] + 1}"
    tab1 = Table(displayName="TabelaDados", ref=range_tabela1)
    tab1.tableStyleInfo = style
    sheet1.add_table(tab1)

    # --- Cabeçalho e tabela da aba Analise_Evento ---
    sheet2 = workbook["Analise_Evento"]
    sheet2["A1"] = "Usuário define qual o evento sob estudo:"
    if not df_analise.empty:
        tipos_encontrados = sorted(set(df_analise["Identificacao"].str[-2:]))
        sheet2["A2"] = f"Equipamentos estudados: {', '.join(tipos_encontrados)}"
        range_tabela2 = f"A5:{get_column_letter(df_analise.shape[1])}{df_analise.shape[0] + 5}"
        tab2 = Table(displayName="TabelaAnalise", ref=range_tabela2)
        tab2.tableStyleInfo = style
        sheet2.add_table(tab2)

        # Ajuste automático das colunas
        for col in sheet2.columns:
            max_len = max(len(str(cell.value)) if cell.value else 0 for cell in col)
            col_letter = get_column_letter(col[0].column)
            sheet2.column_dimensions[col_letter].width = max(max_len + 3, 12)

# ============================================================
# EXPORTAÇÃO CSV
# ============================================================

# CSV dos dados brutos
df.to_csv(OUT_CSV, sep=";", index=False)

# CSV da análise de evento
if not df_analise.empty:
    df_analise.to_csv(OUT_CSV_ANALISE, sep=";", index=False)


# ============================================================
# LOG FINAL
# ============================================================
print(f"✅ Arquivo Excel gerado: {OUT_XLSX}")
print(f"✅ CSV Dados Brutos gerado: {OUT_CSV}")
if not df_analise.empty:
    print(f"✅ CSV Análise de Evento gerado: {OUT_CSV_ANALISE}")
print(f"Linhas totais Dados_Brutos: {len(df)}")
print(f"Linhas Analise_Evento: {len(df_analise)}")

import pandas as pd
import numpy as np

# Arquivos
arquivos = [
    "relatorio_anafas_processado.csv",
    "relatorio_anafas_analise_evento.csv"
]

# Colunas de impedância (ficam NULL se vazias)
colunas_impedancia = [
    "Impedancia_Mod",
    "Impedancia_Ang"
]

for arquivo in arquivos:
    df = pd.read_csv(arquivo, sep=";", dtype=str)

    for col in df.columns:
        # Troca vírgula por ponto
        df[col] = df[col].str.replace(",", ".", regex=False)

        # Se for impedância → vazio vira NULL
        if col in colunas_impedancia:
            df[col] = df[col].replace("", np.nan)
        else:
            # Outras colunas numéricas vazias → 0.0
            df[col] = df[col].replace("", "0.0")

    # Salva CSV pronto para MySQL
    novo_nome = arquivo.replace(".csv", "_mysql_ok.csv")
    df.to_csv(novo_nome, sep=";", index=False, na_rep="NULL")

    print(f"✅ Arquivo gerado: {novo_nome}")